### ISSUE TITLE
Overload functions support

### ISSUE THREAD

**Issue by srdgame** [gengyong/luaaa#35]
Cloud we support overload functions:

```cpp

myCat.def("eat", &&MyCat::eat)
myCat.def("eat", &&MyCat::eat2)

```

or 

``` cpp

myCat.def("eat", 
	[](MyCat* cat, const std::string& some_thing) { return cat->eat(some_thing); }),
	[](MyCat* cat, const Rat& rat) { return cat->eat(rat); }))

```

**Comment by gengyong** [comment]
export them with different name, then do it in lua it makes more sense.

```c++
myCat.def("eatSomething", (void(MyClass::*)(const std::string&))&MyCat::eat)
myCat.def("eatRat",  (void(MyClass::*)(const Rat&))&MyCat::eat)
```

in lua:
```lua
function MyCat:eat(any)
    if isRat(any) then
        self.eatRat(any)
    else 
        self.eatSomething(any)
    end
end
```
Lua script is very good at handling tasks like these.

**Comment by srdgame** [comment]
Thus we have to deliver so with an Lua file. Can this piece of script be run (coded) in cplusplus side, e.g. create an object creation hook or somethings else?

**Comment by gengyong** [comment]
This feature requires runtime dynamic type binding; otherwise, it's impossible to infer matching methods at runtime. As a statically typed language, C++ only supports compile-time type binding, with extremely limited support for runtime dynamic types. Implementing dynamic function matching in C++ is equivalent to creating a new scripting language. We already have Lua, so there's no point in trying to do this in C++.
